---
# tasks file for ansible-kopia
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install gnupg
  ansible.builtin.package:
    name: gnupg
    state: present

- name: Ensure Kopia signing key is installed
  ansible.builtin.apt_key:
    url: "{{ kopia_gpg_key }}"
    state: present

- name: Ensure Kopia repository is in sources list
  ansible.builtin.apt_repository:
    repo: "{{ kopia_apt_repo }}"
    state: present

- name: Install Kopia
  ansible.builtin.package:
    name: kopia
    update_cache: true
    state: present

- name: Add Kopia repository
  ansible.builtin.command: >
    kopia repository create filesystem
    --path={{ kopia_path }}
    --owner-gid={{ kopia_group_gid }}
    --owner-uid={{ kopia_user_uid }}
    --password={{ kopia_repository_password }}
  register: kopia_create_repository
  changed_when: "'found existing data in storage location' not in kopia_create_repository.stderr"
  failed_when: >
    kopia_create_repository.rc != 0 and
    'found existing data in storage location' not in kopia_create_repository.stderr
  notify: Restart kopia

- name: Connect to Kopia repository
  ansible.builtin.command: >
    kopia repository connect filesystem
    --path={{ kopia_path }}
    --password={{ kopia_repository_password }}
  register: kopia_connect_repository
  changed_when: "'already connected' not in kopia_connect_repository.stderr"
  notify: Restart kopia

- name: Add Kopia server users
  ansible.builtin.command: >
    kopia server user add
    {{ item.username }}@{{ item.hostname }}
    --user-password={{ item.password }}
  with_items: "{{ kopia_clients }}"
  register: kopia_add_user
  changed_when: "'already exists' not in kopia_add_user.stderr"
  failed_when: kopia_add_user.rc != 0 and 'already exists' not in kopia_add_user.stderr
  notify: Restart kopia

- name: Start server with TLS Certificate generation for first time
  ansible.builtin.command: >
    timeout 5 kopia server start
    --tls-generate-cert
    --tls-cert-file=/root/kopia.cert
    --tls-key-file=/root/kopia.key
    --address="0.0.0.0:{{ kopia_port }}"
    --server-control-username={{ kopia_control_username }}
    --server-control-password={{ kopia_control_password }}
  register: kopia_start_server
  changed_when: >
    'already exists' not in kopia_start_server.stderr and
    'address already in use' not in kopia_start_server.stderr
  failed_when: >
    kopia_start_server.rc != 124 and
    'already exists' not in kopia_start_server.stderr and
    'address already in use' not in kopia_start_server.stderr
  notify: Restart kopia

- name: Create Kopia create service
  ansible.builtin.template:
    src: ./kopia.service.j2
    dest: /etc/systemd/system/kopia.service
    mode: "0755"
  notify: Restart kopia

- name: Ensure Kopia service is started and enabled
  ansible.builtin.service:
    name: kopia
    state: started
    enabled: true

- name: Get Kopia server certificate
  ansible.builtin.shell: >
    set -o pipefail &&
    openssl x509 -noout -fingerprint -sha256 -inform pem -in /root/kopia.cert |
    tr -d : |
    sed 's/^sha256 Fingerprint=//' | tr '[:upper:]' '[:lower:]'
  args:
    executable: /bin/bash
  register: kopia_server_cert
  changed_when: false

- name: Print Kopia server certificate
  ansible.builtin.debug:
    msg: "SERVER CERT: {{ kopia_server_cert.stdout }}"
